### ISSUE TITLE
Web端举手模式下，多个用户举手，点击全部拒绝，只有第一个会生效，后面的都会提示发送自定义消息失败

### ISSUE THREAD

**Issue by miiiku** [tencentyun/TUIRoom#101]
报错信息打印如下，如果加上一个定时器，每条消息延迟1秒执行则没有这个问题。

![image](https://user-images.githubusercontent.com/19169144/186310053-b15dd3e3-5bb4-42ba-936d-7f5c4cd7762e.png)

**Comment by lixin0** [comment]
该 bug 已修复，辛苦更新 github 代码～
