### ISSUE TITLE
iOS的demo跑不起来，具体可以clone下载跑一下

### ISSUE THREAD

**Issue by lxm1799** [tencentyun/TUIRoom#12]
首页是SDK文件夹中TXLiteAVSDK_ReplayKitExt.framework没有
然后是@import TXLiteAVSDK_ReplayKitExt;报错
接着是TUIRoom混编导入文件有问题。

**Comment by iOSliusen** [comment]
你把这俩文件放到SDK（和example文件夹平级）文件夹下，然后 pod install 就可以了，clone下来的源码中没这俩文件
TXLiteAVSDK_TRTC.framework
TXLiteAVSDK_ReplayKitExt.framework
文件下载地址https://github.com/tencentyun/TRTCSDK/tree/master/iOS/SDK

**Comment by boundlessocean** [comment]
Library not loaded: @rpath/FFMPEG.framework/FFMPEG
Reason: tried: '/usr/lib/swift/FFMPEG.framework/FFMPEG' (no such file),

**Comment by boundlessocean** [comment]
App启动后 报错，Library not loaded: @rpath/FFMPEG.framework/FFMPEG
Reason: tried: '/usr/lib/swift/FFMPEG.framework/FFMPEG' (no such file),
