### ISSUE TITLE
Windows-Mac 无法编译，Git的文档对Qt环境版本描述有误

### ISSUE THREAD

**Issue by jinwuZhu** [tencentyun/TUIRoom#29]
希望这个可以给其他遇到类似问题的用户参考一下。官方也最好注明一下
Step1: Clone 下载源码
Step2: 打开RoomApp.vcxproj项目工程文件
Step3:在项目右键>>属性>>QtProjectSetting>>General>>QtInstallation 重新选择一下目前已经安装的Qt环境（最好和Demo一致）
![image](https://user-images.githubusercontent.com/90186447/160373388-a29e6876-52ce-4705-882c-4c2e1ade7ade.png)

**Comment by Tencent-Alice** [comment]
您好 根据您的问题  有报错信息吗

Step1: Clone 下载源码

Step2: 打开RoomApp.vcxproj项目工程文件

Step3:在项目右键>>属性>>QtProjectSetting>>General>>QtInstallation 重新选择一下目前已经安装的Qt环境（最好和Demo一致）
技术问题 欢迎交流 Q2562367495 注明来意
