### ISSUE TITLE
在pc端electron创建的群组，在安卓端上加入群组提示 invalid group id

### ISSUE THREAD

**Issue by li2301313** [tencentyun/TUIRoom#40]
sdkappid: 1400664679
roomid: 7633
userid: 58684
时间： 2022年4月18日15:52:01
问题描述：官方demo TRTCSimpleDemo 集成 tim-js-sdk 后创建会议临时类型的分组，创建成功后在安卓端集成[TUIVoiceRoom](https://github.com/tencentyun/TUIVoiceRoom)[](https://user-images.githubusercontent.com/25633267/163776574-d71ed1d6-48a8-4ba9-b7b3-61c002874563.png)[](https://user-images.githubusercontent.com/25633267/163776600-a0b59b88-f4d2-49e5-84a0-d27c865af600.png)加入房间的提示 invalid group id

![QQ截图20220418155718](https://user-images.githubusercontent.com/25633267/163783318-5b67914d-afb8-4873-81ec-77986f80e546.png)

安卓端
![QQ截图20220418155756](https://user-images.githubusercontent.com/25633267/163783387-bace8230-0005-4cd5-9a9e-549b8f8df9a8.png)

[LiteAV_C_2022-04-18_12_04_45_698.zip](https://github.com/tencentyun/TUIRoom/files/8504783/LiteAV_C_2022-04-18_12_04_45_698.zip)

**Comment by MinTate** [comment]
<img width="1158" alt="image" src="https://user-images.githubusercontent.com/16069375/163793116-f374e1f2-a1a2-45a3-a5de-6ae5ef3d54b8.png">

从日志这边，是没有登录，是有修改过什么代码？？

**Comment by li2301313** [comment]
登陆成功后也是提示  invalid group id ，

**Comment by MinTate** [comment]
已解决，TUIRoom的房间号是字符串房间号，格式：“Room_xxxx”，（为了和其他业务有隔离，有个默认前缀）

**Comment by gu6541515** [comment]
我这边在接入会议的同时，也集成了音视频功能，在会议的时候，会收到音视频的来电邀请，能不能把会议在线的时候，做到像音视频一样提示正在通话中（占线）
