### ISSUE TITLE
微信小程序demo无法启动

### ISSUE THREAD

**Issue by utah2016** [tencentyun/TUIRoom#45]
VM93:9 app.js错误:
 Error: module 'lib/TUIRoom/lib/index.js' is not defined

Uncaught FrameworkError 
 module 'lib/TUIRoom/lib/index.js' is not defined 
 Error: module 'lib/TUIRoom/lib/index.js' is not defined

VM20 WAServiceMainContext.js:2 Error: module 'lib/TUIRoom/lib/index.js' is not defined
    at d (VM35 WASubContext.js:2)

**Comment by jiushu531** [comment]
开发者工具位添加ts支持，在 project.config.json 文件中，修改 setting 下的 useCompilerPlugins 字段为 ["typescript", "sass"]。

**Comment by MinTate** [comment]
已解决，参照文档执行即可~
